version: '3'
services:
  cygnomatic_workspace:
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      - ${HOME}/.ssh/:/home/ros/.ssh/:ro
    environment:
      DISPLAY: "${DISPLAY}"
      WAYLAND_DISPLAY: "${WAYLAND_DISPLAY}"
      XDG_RUNTIME_DIR: "${XDG_RUNTIME_DIR}"
      PULSE_SERVER: "${PULSE_SERVER}"
      LIBGL_ALWAYS_SOFTWARE: "1"
